### ISSUE TITLE
Exercise 2: no interface configuration after removing link

### ISSUE THREAD

**Issue by daniele-moro** [opennetworkinglab/ngsdn-tutorial#16]
After removing and re-adding the link `leaf1-h1a`via Mininet CLI (`link leaf1 h1a down` and `link leaf1 h1a up`), the configuration of the interface `h1a-eth0` is lost. The ping between `h1a` and `h1b`, then, fails with the following message `connect: Network is unreachable`.

**Comment by daniele-moro** [comment]
@bocon13

**Comment by ccascone** [comment]
We might need to modify the host class in topo.py to re-add the IP configuration after the interface is brought back up.

**Comment by bocon13** [comment]
Rather than down both sides of the interface, I've updated the instructions to only disable the switch side: `mininet> sh ifconfig leaf1-eth3 down` 

This appears to avoid deleting the host-side config.
