### ISSUE TITLE
Openconfig yang files not included in container

### ISSUE THREAD

**Issue by ComposMin** [opennetworkinglab/ngsdn-tutorial#21]
Exercise 2 has a section with this comment:

These models have already been loaded into the yang-tools container in the /models directory.

I'm not sure that the models have been included in the docker container version. Examining the Makefile shows that only a single file is mounted in the /models directory. See:

yang-tools:
	docker run --rm -it -v ${curr_dir}/yang/demo-port.yang:/models/demo-port.yang ${YANG_IMG}

This makes the subsequent command in the tutorial fail.

**Comment by ComposMin** [comment]
I can help fix this problem, but I can't find the source code and build of the docker container.
https://hub.docker.com/r/bocon/yang-tools

Who is the mysterious bocon?

**Comment by ccascone** [comment]
The openconfig models are part of the docker image, they are not mounted.

```
➜  ngsdn-tutorial git:(master) ✗ make yang-tools
docker run --rm -it -v /Users/carmelo/workspace/ngsdn-tutorial/yang/demo-port.yang:/models/demo-port.yang bocon/yang-tools:latest
bash-4.4# ls -l openconfig/
total 44
drwxr-xr-x    2 root     root          4096 Sep  6  2019 acl
drwxr-xr-x    2 root     root          4096 Sep  6  2019 interfaces
drwxr-xr-x    2 root     root          4096 Sep  6  2019 lacp
-rw-r--r--    1 root     root          6454 Sep  6  2019 openconfig-extensions.yang
drwxr-xr-x    2 root     root          4096 Sep  6  2019 optical-transport
drwxr-xr-x    2 root     root          4096 Sep  6  2019 platform
drwxr-xr-x    2 root     root          4096 Sep  6  2019 qos
drwxr-xr-x    2 root     root          4096 Sep  6  2019 system
drwxr-xr-x    2 root     root          4096 Sep  6  2019 types
drwxr-xr-x    2 root     root          4096 Sep  6  2019 vlan
