### ISSUE TITLE
TODOs from Stanford Tutorial

### ISSUE THREAD

**Issue by bocon13** [opennetworkinglab/ngsdn-tutorial#31]
- [x] P4 syntax highlighting in VSCode (@ccascone)
- [x] install tmux in workspace (@ccascone)
- [x] instructions for exercise 1 & 2 should have participants keep the pings running (@pudelkom)
- [x] exercise 3 readme, we don't expect any links to be present -- fix description  (@pudelkom)
- [x] fix attack filter for ssh-mux (@Yi-Tseng)
- [x] multiple web shells (@Yi-Tseng) [start with 2 hardcoded]
- [x] ONOS UI loads insecure scripts (@bocon13)
- [ ] consider disabling user/pass for ONOS UI (@bocon13)
- [ ] bug: tty-share doesn't let you paste large blocks of text

**Comment by bocon13** [comment]
@ccascone @Tseng-Yi here were my notes from the Stanford tutorial

**Comment by Yi-Tseng** [comment]
https://github.com/opennetworkinglab/ngsdn-tutorial/blob/stanford19/app/src/main/java/org/onosproject/ngsdn/tutorial/L2BridgingComponent.java#L213

Should be "FF:FF:FF:FF:FF:FF"
