### ISSUE TITLE
Issue with netcfg

### ISSUE THREAD

**Issue by drobinkent** [opennetworkinglab/ngsdn-tutorial#38]
In the tutorial, each leaf switch's port 1 and 2 are connected to spine switches. In the netcfg.json file if I write configuration for those 2 ports ONOS fails to configure ports. What's the exact reason of this behavior? Can anyone please explain please?

**Comment by ccascone** [comment]
I'm not sure what exactly is the issue you are seeing, but in general, the tutorial app does not expect a configuration for infrastructure ports, i.e., those connecting a leaf with a spine. The app expects a configuration for the edge ports (interface IPv6 address/subnet), based on that it will generate flow rules to eventually forward packets via the infrastructure ports.
