### ISSUE TITLE
Reading Direct Counter Value

### ISSUE THREAD

**Issue by johnhauhnar** [opennetworkinglab/ngsdn-tutorial#40]
Hi,
   I was trying out this tutorial specifically the one explained in "EXERCISE-1.md"
I was able to send ping packet between the hosts after programming the table entries from P4 Runtime shell.

Then I tried reading the counter values, but I could not seem to do so..
Can you quickly point me how to read the direct/in-direct counter from p4runtime shell?

Below is the logs of my attempt to read the counter values:
-----------------------------------------------------------------
P4Runtime sh >>> direct_counters
acl_table_counter
l2_exact_table_counter
l2_ternary_table_counter
my_station_table_counter
ndp_reply_table_counter
routing_v6_table_counter

P4Runtime sh >>> direct_counters["acl_table_counter"]
Out[6]:
preamble {
  id: 318773822
  name: "acl_table_counter"
  alias: "acl_table_counter"
}
spec {
  unit: BOTH
}
direct_table_id: 33557865 ("IngressPipeImpl.acl_table")

P4Runtime sh >>> direct_counter_entry["acl_table_counter"]
Out[7]:
table_entry {
  table_id: 33557865 ("IngressPipeImpl.acl_table")
}

P4Runtime sh >>> for dce in direct_counter_entry["acl_table_counter"].read:
            ...:         print(dce)
            ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-a0dc960364b5> in <module>
----> 1 for dce in direct_counter_entry["acl_table_counter"].read:
      2         print(dce)
      3

TypeError: 'method' object is not iterable

P4Runtime sh >>> dce = direct_counter_entry["acl_table_counter"].read()

P4Runtime sh >>> print dce
<p4runtime_sh.shell._EntityBase.read.<locals>._EntryIterator object at 0x7f66241b0208>

P4Runtime sh >>>

**Comment by Yi-Tseng** [comment]
Maybe you can try putting a lambda to the read function
`direct_counter_entry["acl_table_counter"].read(lambda dce: print(dce))`

**Comment by johnhauhnar** [comment]
> Maybe you can try putting a lambda to the read function
> `direct_counter_entry["acl_table_counter"].read(lambda dce: print(dce))`

Thanks for the suggestion..
I tried and below is what I got:-
========================
P4Runtime sh >>> direct_counters                                                                                                                    
acl_table_counter
l2_exact_table_counter
l2_ternary_table_counter
my_station_table_counter
ndp_reply_table_counter
routing_v6_table_counter

P4Runtime sh >>>  direct_counter_entry["acl_table_counter"].read(lambda dce: print(dce))                                                            
---------------------------------------------------------------------------
P4RuntimeException                        Traceback (most recent call last)
<ipython-input-16-488b2ed60c3a> in <module>
----> 1 direct_counter_entry["acl_table_counter"].read(lambda dce: print(dce))

/p4runtime-sh/p4runtime_sh/shell.py in read(self, function)
   1821         <self>.read(lambda c: print(c))
   1822         """
-> 1823         return super().read(function)
   1824
   1825

/p4runtime-sh/p4runtime_sh/shell.py in read(self, function)
    708             return _EntryIterator(self, iterator)
    709         else:
--> 710             for x in _EntryIterator(self, iterator):
    711                 function(x)
    712

/p4runtime-sh/p4runtime_sh/p4runtime.py in handle(*args, **kwargs)
    132             return f(*args, **kwargs)
    133         except grpc.RpcError as e:
--> 134             raise P4RuntimeException(e) from None
    135     return handle
    136

P4RuntimeException: P4Runtime RPC error (UNIMPLEMENTED):

P4Runtime sh >>>

**Comment by ccascone** [comment]
Closing as this is not related to this repo (ngsdn-tutorial). The feature seems to be `UNIMPLEMENTED` by the switch. If I remember well reading all direct counters for a given table is not supported by [BMv2](https://github.com/p4lang/behavioral-model) and/or [PI](https://github.com/p4lang/PI).
