### ISSUE TITLE
make app-reload

### ISSUE THREAD

**Issue by 1760947562** [opennetworkinglab/ngsdn-tutorial#49]
when I type "make app-reload"in a terminal window,it display some mistakes:

*** Uninstalling app from ONOS (if present)...
curl --fail -sSL --user onos:rocks --noproxy localhost -X DELETE http://localhost:8181/onos/v1/applications/org.onosproject.ngsdn-tutorial

*** Installing and activating app in ONOS...
curl --fail -sSL --user onos:rocks --noproxy localhost -X POST -HContent-Type:application/octet-stream \
	'http://localhost:8181/onos/v1/applications?activate=true' \
	--data-binary @app/target/ngsdn-tutorial-1.0-SNAPSHOT.oar
{"name":"org.onosproject.ngsdn-tutorial","id":192,"version":"1.0.SNAPSHOT","category":"Traffic Steering","description":"Provides IPv6 routing capabilities to a leaf-spine network of P4 switches","readme":"Provides IPv6 routing capabilities to a leaf-spine network of P4 switches","origin":"p4.org","url":"http://www.onosproject.org","featuresRepo":"mvn:org.onosproject/ngsdn-tutorial/1.0-SNAPSHOT/xml/features","state":"ACTIVE","features":["ngsdn-tutorial"],"permissions":[],"requiredApps":["org.onosproject.drivers.bmv2","org.onosproject.lldpprovider","org.onosproject.hostprovider"]}

**Comment by charlesmcchan** [comment]
Looks like it is doing what app-reload suppose to do. I didn't spot the error message here.

**Comment by ccascone** [comment]
Closing issue as this is the expected output. Feel free to re-open if there's something more.
