### ISSUE TITLE
Tcpdump

### ISSUE THREAD

**Issue by sheenB** [opennetworkinglab/ngsdn-tutorial#50]
Hi,
why is it not possible to start a tcpdump?
Error: tcpdump: error while loading shared libraries: libcrypto.so.1.0.2: cannot stat shared object: Permission denied

best regards
sheenB

**Comment by ederollora** [comment]
That looks like a permission error. Have you tried with "sudo" in front of the command? Elevated permissions are normally required to capture packets.

**Comment by sheenB** [comment]
Hi,
I had allready try it with "sudo" in front but the error is the same.

**Comment by ederollora** [comment]
Is tcpdump running on a container? alternatively, does your user have elevated privileges?

**Comment by sheenB** [comment]
Hi,
thenk you for your help. Now i have finde a solution. this is my solution:
First created a TCPdump container:
docker build -t tcpdump - <<EOF 
FROM ubuntu 
RUN apt-get update && apt-get install -y tcpdump  
EOF

Then i open a new shell and link the TCPdump container:
docker run -it --net=container:mininet tcpdump tcpdump -i leaf1-eth3

**Comment by ederollora** [comment]
If you had the problem in a container then I was going to recommend [this solution](https://github.com/moby/moby/issues/14140#issuecomment-114898486) which suggests:

`RUN apt-get install -y tcpdump
# HACK around https://github.com/dotcloud/docker/issues/5490
RUN mv /usr/sbin/tcpdump /usr/bin/tcpdump`

If you solved the issue, please, close it :)
