### ISSUE TITLE
Mininet issue: Error: Cannot connect to display

### ISSUE THREAD

**Issue by asydney** [opennetworkinglab/ngsdn-tutorial#68]
Hi NGSDN folks,              
                           I'm using the vm image you provided for the tutorial. When I attempt to pull an xterm for any node, I get the following:

mininet> xterm h1a
Error: Cannot connect to display

Is this the expected behavior? In particular, are there other configurations that must be set for xterm to work for this particular vm? If yes, can you kindly point me to the documentation?

BTW. This is a great tutorial! 

Thanks!
-Syd

**Comment by charlesmcchan** [comment]
Looks like this is a duplication of #56. Feel free to re-open if it is not.
