### ISSUE TITLE
Possible typo in SRv6 rule for Exercise 6

### ISSUE THREAD

**Issue by asydney** [opennetworkinglab/ngsdn-tutorial#70]
Hi NGSDN folks,
                            In exercise 6, it appears that IP mentioned in the text for inserting the SRv6 rules, contains the wrong IP for h4 (i.e. 2001:1:4::1 as opposed to 2001:2:4::1). In particular, please update Section 4 as follows(https://github.com/opennetworkinglab/ngsdn-tutorial/blob/advanced/EXERCISE-6.md#4-inserting-srv6-policies) :

Change:
"""
Insert the SRv6 policy from h2 to h4 on leaf1 (through spine1 and leaf2)
onos> srv6-insert device:leaf1 3:201:2:: 3:102:2:: 2001:1:4::1
"""

To:
'''
srv6-insert device:leaf1 3:201:2:: 3:102:2:: 2001:2:4::1
'''

Cheers!
-Syd

**Comment by charlesmcchan** [comment]
Please submit a pull request. Thanks.
