### ISSUE TITLE
How to experiment with other app codebases (e.g. Trellis) using ngsdn-tutorial tools?

### ISSUE THREAD

**Issue by asydney** [opennetworkinglab/ngsdn-tutorial#71]
Hi NGSDN folks,
                          This tutorial has been awesome! I got to use the Trellis app in exercise 7, but not the actual code base (e.g. to see/experiment with components such as segmentrouting, build changes and load the updated app into onos). How can I interact with the trellis code base (or any of the applications listed in ~/onos/apps within the onos container) using the same Intellij setup that ships with the tutorial?

Thanks,
-Syd

**Comment by charlesmcchan** [comment]
You can find the answer here: [Development Environment Setup](https://wiki.onosproject.org/display/ONOS/Development+Environment+Setup)
ONOS is using Bazel as the build system so please follow [Using an IDE with ONOS 1.14 or higher (Bazel build)](https://wiki.onosproject.org/pages/viewpage.action?pageId=28836246)
Trellis apps is using Maven instead so please follow [Use an IDE with Maven](https://wiki.onosproject.org/pages/viewpage.action?pageId=10558601)
