### ISSUE TITLE
How do we automatically generate mininet topology and netcfg files?

### ISSUE THREAD

**Issue by asydney** [opennetworkinglab/ngsdn-tutorial#73]
Hi NGSDN folks,
                          Is there some standard way of automating the generation of the topology (e.g. topo.py) and netcfg files (e.g. netcfg.json)? Or is the expectation that we do this manually?

Cheers!
-Syd

**Comment by charlesmcchan** [comment]
We don't have such config generation tool yet.
It is possible to generate netcfg from topology python file. We are also thinking integrating with 3rd party hardware inventory tool such as NetBox and use the topology to generate netcfg automatically. But none of those has been done yet.

**Comment by asydney** [comment]
Thanks for the reply :)
