### ISSUE TITLE
Help please - main.p4

### ISSUE THREAD

**Issue by santorsula** [opennetworkinglab/ngsdn-tutorial#74]
I followed the exercise documentation, but during compilation an error occurs. Could someone help me with this matter, please?

Exercise 4: Enabling ONOS Built-in Services
https://github.com/opennetworkinglab/ngsdn-tutorial/blob/advanced/EXERCISE-4.md

main.p4
https://github.com/opennetworkinglab/ngsdn-tutorial/blob/advanced/p4src/main.p4

Error during compilation:

*** Building P4 program...
docker run --rm -v /home/sdn/ngsdn-tutorial:/home/sdn/ngsdn-tutorial -w /home/sdn/ngsdn-tutorial opennetworking/p4c:stable \
        p4c-bm2-ss --arch v1model -o p4src/build/bmv2.json \
        --p4runtime-files p4src/build/p4info.txt --Wdisable=unsupported \
        p4src/main.p4
p4src/main.p4(551): [--Werror=not-found] error: cpu_in: Not found declaration
        if (cpu_in.ingress == 255) {
            ^^^^^^
Makefile:98: recipe for target 'p4-build' failed
make: *** [p4-build] Error 1

Thank you to everyone in the group.

--
Regards,

Fernando Henrique Santorsula

**Comment by ederollora** [comment]
It seems that:

- you might not have declared the `cpu_in` header, missing declaration:
   ```
    struct headers_t {
        ( . . . )
        cpu_in_t cpu_in;
    }
    ```
- or, that you probably have to refer to it as `hdr.cpu_in.ingress`
- or, if this is a variable, you might have also not declared it: `bit<n> cpu_in;`

Regards,

**Comment by santorsula** [comment]
Hello, thanks for the feedback, I confess I hadn't done it, I just did it in the comments, but I don't know if I did it correctly:

struct headers_t {
     cpu_out_header_t cpu_out;
     cpu_in_t cpu_in;
 }


I am a beginner in P4 and did not understand very well what needs to be changed in exercise 4, I did what you are asking for, but I do not know if I am doing it correctly, could you help me please? Result after I did this procedure that informed me:

*** Building P4 program...
docker run --rm -v /home/sdn/ngsdn-tutorial:/home/sdn/ngsdn-tutorial -w /home/sdn/ngsdn-tutorial opennetworking/p4c:stable \
        p4c-bm2-ss --arch v1model -o p4src/build/bmv2.json \
        --p4runtime-files p4src/build/p4info.txt --Wdisable=unsupported \
        p4src/main.p4
p4src/main.p4(209):syntax error, unexpected IDENTIFIER "cpu_in_t"
     cpu_in_t
     ^^^^^^^^
error: 1 errors encountered, aborting compilation
Makefile:98: recipe for target 'p4-build' failed
make: *** [p4-build] Error 1

**Comment by ederollora** [comment]
Hi,

My recommendation is that your first complete the P4 tutorial: [https://github.com/p4lang/tutorials/](https://github.com/p4lang/tutorials/). You will most likely feel lost in most exercises of NG SDN repo without having a basic understanding of P4. That tutorial will get you up to date in the language to some extent.

In terms of your problem, I was just writing some general code, so my examples will probably not work by just copy pasting it. In your case, the header is already declared (as per your link exercise). So do not modify this line:

```
struct parsed_headers_t {
    ...
    cpu_in_header_t cpu_in;
    ...
}
```

According to the exercise and your error I guess what you are trying to do is complete this part of the exercise:
```
if (standard_metadata.egress_port == CPU_PORT) {
    // *** TODO EXERCISE 4
    // Implement logic such that if the packet is to be forwarded to the
    // CPU port, e.g., if in ingress we matched on the ACL table with
    // action send/clone_to_cpu...
    // 1. Set cpu_in header as valid
    // 2. Set the cpu_in.ingress_port field to the original packet's
    //    ingress port (standard_metadata.ingress_port).
}
```

In this case you need to:
1) use `setValid()` to set the `cpu_in` header valid.

![image](https://user-images.githubusercontent.com/3457431/111924583-a8227700-8aa5-11eb-829c-20534757fdea.png)
(info: [https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-ops-on-hdrs](https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-ops-on-hdrs))

2) Assign the `ingress_port` field the packet's ingress port (which is stored in `standard_metadata` as `ingress_port`, i.e. ` standard_metadata.ingress_port`) to `cpu_in`'s `ingress_port` field. That is: `hdr.cpu_in.ingress_port` equals `standard_metadata.ingress_port`;

To refer to the `cpu_in` header be sure you refer to it as `hdr.cpu_in` always, else making it valid and assigning a value to its `ingress_port` field will be wrong. I still recommend you to do the aforementioned P4 tutorial. I am letting you complete the exercise but if you need further help on the exact code let us know.

Regards,

**Comment by santorsula** [comment]
Hello how are you? Thank you very much again for your feedback and for your help, or following your advice to start with the basic tutorial, I confess that I didn't quite understand the logic of P4, but in this exercise I left this area of ​​the main.p4 file like this:

struct parsed_headers_t {
    ...
    cpu_in_header_t cpu_in;
    ...
}

I left this other configuration as instructed:
setValid()

However, I still have an error that I could not identify or understand the problem:
p4src/main.p4(555): [--Werror=not-found] error: cpu_in: Not found declaration
        if (cpu_in.ingress_port.egress_port == 255) {
		
		
What I find strange is that I declared it as requested by the exercise, I'm a little lost, sorry! Thanks for support friend.

**Comment by ederollora** [comment]
Hi,

Ok so let me explain some parts.

This part seems wrong for several reasons:

`if (cpu_in.ingress_port.egress_port == 255) {`

The original code wrote this line instead, and it should stay in the same way (AFAIK):
```
if (standard_metadata.egress_port == CPU_PORT) {
}
```

The errors also refers to the fact that `cpu_in` should be written `hdr.cpu_in` instead. Finally, `ingress_port` is a field in the `cpu_in` header but `egress_port` is not, so a reference like `cpu_in.ingress_port.egress_port` is wrong.

You should write something like:

```
if (standard_metadata.egress_port == CPU_PORT) { 
    hdr.cpu_in.setValid();
    hdr.cpu_in.ingress_port = standard_metadata.ingress_port;
    hdr.cpu_in._pad = 0;
}
```

This piece of code is trying express this: "So... if the output port that we defined in the Ingress part of the pipeline is the actual CPU port (so we are sending this packet to the controller), then we have to first make `cpu_in` header valid because we need to prepend it to the packet. In this way, the controller can know the `ingress_port` from which it came from."

Once again, I really encourage you to first complete the P4 tutorial from the link I sent in my previous message. I imagine it is difficult to understand some of the suggestions I make here.

If you need help to understand any exercises from the P4 tutorial you can preferably write to the P4 Slack or the p4-dev mailing list but you can write to me if you want to.

Regards,

**Comment by santorsula** [comment]
Hello,

I appreciate the explanation and for testing I used this block of code that you sent me and I think the errors have grown, but no problem, I will follow the basic P4 documentation to understand the language and then I will go to the basic tutorials, I need to understand every line of code for me to develop my project, but I thank you for your help and I will leave these errors there and get P4 to study from scratch, if not, I will not be able to evolve at all, if I solve the problem it will be very good , but I didn’t understand the logic of the language, I need this for my project that is in short order, but I will follow your advice and thank you very much for helping me, sorry to take your time, thank you very much.


root@tutorial-vm:/home/sdn/ngsdn-tutorial# make p4-build
*** Building P4 program...
docker run --rm -v /home/sdn/ngsdn-tutorial:/home/sdn/ngsdn-tutorial -w /home/sdn/ngsdn-tutorial opennetworking/p4c:stable \
        p4c-bm2-ss --arch v1model -o p4src/build/bmv2.json \
        --p4runtime-files p4src/build/p4info.txt --Wdisable=unsupported \
        p4src/main.p4
p4src/main.p4(502): [--Werror=type-error] error: Condition of IfStatement does not evaluate to a bool but void
        if (hdr.cpu_out.setValid()) {
        ^^
p4src/main.p4(556): [--Werror=type-error] error: Field cpu_in is not a member of structure header cpu_in_header_t
      hdr.cpu_in.setValid();
          ^^^^^^
p4src/main.p4(168)
header cpu_in_header_t {
       ^^^^^^^^^^^^^^^
p4src/main.p4(557): [--Werror=type-error] error: Field cpu_in is not a member of structure header cpu_in_header_t
      hdr.cpu_in.ingress_port = standard_metadata.ingress_port;
          ^^^^^^
p4src/main.p4(168)
header cpu_in_header_t {
       ^^^^^^^^^^^^^^^
p4src/main.p4(558): [--Werror=type-error] error: Field cpu_in is not a member of structure header cpu_in_header_t
      hdr.cpu_in._pad = 0;
          ^^^^^^
p4src/main.p4(168)
header cpu_in_header_t {
       ^^^^^^^^^^^^^^^
p4src/main.p4(627): [--Werror=legacy] error: main: Cannot unify parameter hdr with hdr because they have different directions
) main;
  ^^^^
p4src/main.p4(550)
       hdr,
       ^^^
/usr/share/p4c/p4include/v1model.p4(423)
control Egress<H, M>(inout H hdr,
                             ^^^
Makefile:98: recipe for target 'p4-build' failed
make: *** [p4-build] Error 1

**Comment by ederollora** [comment]
Hi


For clarity, I will try to point out some errors I see from your last message:

1) `if (hdr.cpu_out.setValid()) {` should be `if (hdr.cpu_out.isValid()) {`. setValid makes a header valid (so it can be deparsed and put into the wire) and `isValid()` is letting you know if the header is valid or not.

2 and 3) Second error "Field cpu_in is not a member of structure header cpu_in_header_t" is confusing. You should have both defined and declared the cpu_in header. The following structures should be in your program:

```
@controller_header("packet_in")
header cpu_in_header_t {
    port_num_t  ingress_port;
    bit<7>      _pad;
}
```

and 

```
struct parsed_headers_t {
    cpu_out_header_t cpu_out;
    cpu_in_header_t cpu_in;
   // more headers
}
```

4) The rest of the errors are difficult to clarify with the original code (you can attach a file in next messages you post, so we can debug it. It looks like, maybe, you might have not closed some structures or control blocks.

Don't worry about the time. I think you can come to anyone on the ONOS or P4 community and everyone will try to help as long as they have free time. I definitely think that the P4 tutorials will bring you the knowledge you need before you face the NG-SDN tutorials. It will be of much help. 

Let us know if you need more help. You can close the issues if you want to.

Cheers,

**Comment by santorsula** [comment]
OK.
